
-- QUERY DATABSE 
SELECT * FROM 
employees;

--SELECT count(first_name)
--FROM employees
--WHERE birth_date BETWEEN '1952-01-01' AND '1955-12-31';

-- BORN IN 1952
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1952-01-01' AND '1952-12-31';

-- BORN IN 1953
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1953-01-01' AND '1953-12-31';

-- BORN IN 1954
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE BIRTH_DATE BETWEEN '1954-01-01' AND '1954-12-31';

-- Retirement eligibility
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE (BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
AND (HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31');

-- Retirement eligibility count
SELECT count(FIRST_NAME)
FROM EMPLOYEES
WHERE (BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
AND (HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31');

-- Create New retirement table from existing employee table
SELECT emp_no, first_name, last_name
INTO retirement_info
FROM employees
WHERE (birth_date BETWEEN '1952-01-01' AND '1955-12-31')
AND (hire_date BETWEEN '1985-01-01' AND '1988-12-31');

-- Check the table 
SELECT * FROM retirement_info;

-- Remove/"Drop" table
-- DROP TABLE CURRENT_EMP;

-- joining tables 
SELECT 
D.DEPT_NAME
,DM.EMP_NO
,DM.FROM_DATE
,DM.TO_DATE
FROM DEPARTMENTS AS D
INNER JOIN DEPT_MANAGER AS DM ON (D.DEPT_NO = DM.DEPT_NO)
;

-- Joining retirement_info and dept_emp tables
SELECT 
RI.EMP_NO
,RI.FIRST_NAME
,RI.LAST_NAME
,DE.TO_DATE
FROM RETIREMENT_INFO AS RI
LEFT JOIN DEPT_EMP AS DE ON (RI.EMP_NO = DE.EMP_NO)
;

-- SELECT ELIGIBLE RETIREMENT EMPS THAT ARE CURRENTLY EMPLOYED 
SELECT 
RI.EMP_NO
,RI.FIRST_NAME
,RI.LAST_NAME
,DE.TO_DATE
INTO CURRENT_EMP
FROM RETIREMENT_INFO AS RI 
LEFT JOIN DEPT_EMP AS DE ON (RI.EMP_NO = DE.EMP_NO)
WHERE DE.TO_DATE=('9999-01-01')
;

SELECT *
FROM CURRENT_EMP;

-- Count of current emps that are retirement eligible 
SELECT COUNT(EMP_NO)
FROM CURRENT_EMP;

-- emp count by dept #
SELECT 
COUNT(CE.EMP_NO)
,DE.DEPT_NO
,D.DEPT_NAME
INTO DEPT_ELIGIBLE_RETIREES
FROM CURRENT_EMP AS CE
LEFT JOIN DEPT_EMP AS DE ON (CE.EMP_NO = DE.EMP_NO)
LEFT JOIN DEPARTMENTS AS D ON (DE.DEPT_NO = D.DEPT_NO)
GROUP BY DE.DEPT_NO, D.DEPT_NAME
ORDER BY DE.DEPT_NO
;

SELECT *
FROM SALARIES
ORDER BY TO_DATE DESC;

-- EMPLOYEE TABLE
SELECT 
E.EMP_NO, 
E.FIRST_NAME, 
E.LAST_NAME, 
E.GENDER, 
DE.TO_DATE,
S.SALARY
INTO EMP_INFO 
FROM EMPLOYEES AS E
INNER JOIN DEPT_EMP AS DE ON (E.EMP_NO = DE.EMP_NO)
INNER JOIN SALARIES AS S ON (E.EMP_NO = S.EMP_NO)
WHERE (E.BIRTH_DATE BETWEEN '1952-01-01' AND '1955-12-31')
AND (E.HIRE_DATE BETWEEN '1985-01-01' AND '1988-12-31')
AND DE.TO_DATE = '9999-01-01';


-- MANAGER TABLE 
SELECT 
D.DEPT_NO, 
D.DEPT_NAME,
DM.EMP_NO,
CE.FIRST_NAME,
CE.LAST_NAME,
DM.FROM_DATE, 
DM.TO_DATE
INTO MANAGER_INFO 
FROM DEPARTMENTS AS D
INNER JOIN DEPT_MANAGER AS DM ON (D.DEPT_NO = DM.DEPT_NO)
INNER JOIN CURRENT_EMP AS CE ON (DM.EMP_NO = CE.EMP_NO);

SELECT * FROM CURRENT_EMP;
-- DROP TABLE EMP_INFO;

-- DEPARTMENT TABLE 
SELECT 
CE.EMP_NO
,CE.FIRST_NAME
,CE.LAST_NAME
,D.DEPT_NAME
INTO DEPT_INFO
FROM CURRENT_EMP AS CE
INNER JOIN DEPT_EMP AS DE ON (CE.EMP_NO = DE.EMP_NO)
INNER JOIN DEPARTMENTS D ON (DE.DEPT_NO = D.DEPT_NO);


SELECT 
EMP_NO
,FIRST_NAME
,LAST_NAME
,DEPT_NAME
FROM DEPT_INFO 
WHERE DEPT_NAME = 'Sales';

SELECT 
EMP_NO
,FIRST_NAME
,LAST_NAME
,DEPT_NAME
FROM DEPT_INFO 
WHERE DEPT_NAME IN ('Sales','Development');

